# Generated by Django 5.1.8 on 2025-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialbank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("Commercial", "Commercial Bank of Ethiopia"),
                    ("Awash", "Awash Bank"),
                    ("Dashen", "Dashen Bank"),
                    ("Mela", "Mela Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
