# Generated by Django 5.1.8 on 2025-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0003_alter_commercialbank_bank_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commercialbank",
            name="bank_type",
        ),
    ]
