# Generated by Django 5.1.8 on 2025-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0004_remove_commercialbank_bank_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_id", models.CharField(max_length=255, unique=True)),
                ("access_secret", models.CharField(max_length=255, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
