# Generated by Django 5.1.8 on 2025-05-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0005_accesskey"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialbank",
            name="access_key",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banks.accesskey",
            ),
        ),
    ]
