# Generated by Django 5.1.8 on 2025-05-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0006_commercialbank_access_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesskey",
            name="raw_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="accesskey",
            name="access_secret",
            field=models.CharField(max_length=255),
        ),
    ]
