# Generated by Django 5.1.8 on 2025-05-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0007_accesskey_raw_secret_alter_accesskey_access_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesskey",
            name="raw_secret",
        ),
        migrations.AlterField(
            model_name="accesskey",
            name="access_secret",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
