# Generated by Django 5.1.8 on 2025-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
