# Generated by Django 5.1.8 on 2025-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Endpoint to notify about incoming transactions",
                null=True,
            ),
        ),
    ]
