# Generated by Django 5.1.8 on 2025-05-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_bankaccount_webhook_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemporaryCode",
        ),
        migrations.DeleteModel(
            name="VerificationCode",
        ),
    ]
