# Generated by Django 5.1.8 on 2025-04-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_centralbankaccount_interbanktransfer"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="central_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.centralbankaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="destination_account",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
