# Generated by Django 5.1.8 on 2025-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interbanksettlement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
