# Generated by Django 5.1.8 on 2025-04-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_centralbankaccount_interbanktransfer"),
        ("transactions", "0002_transaction_central_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.userbankaccount",
            ),
        ),
    ]
