# Generated by Django 5.1.8 on 2025-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_interbanksettlement_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
