# Generated by Django 5.1.8 on 2025-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("INTERBANK", "Interbank Transfer"),
                    ("INTRABANK", "Intrabank Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
