# Generated by Django 5.1.8 on 2025-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
